# Generated by Django 5.0.6 on 2024-06-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=150)),
                ('band_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
