# Generated by Django 5.0.6 on 2024-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'pending'), ('PR', 'processing'), ('SH', 'shipped'), ('DE', 'delivered')], default='pending', max_length=30),
        ),
    ]
